= Philips Hue BLE
Dimitri Fedorov <df.41356@gmail.com>

This project is tested with https://www.philips-hue.com/en-us/p/hue-white-ambiance-1-pack-e26/046677548490[Philips Hue White Ambiance BLE bulb].

The bulb on MacOS X should work out of the box.
If it is not, connect and pair it via Philips Hue mobile app, then factory reset the bulb.

Bulb is advertising single service with short UUID `fe0f` or `0000fe0f-0000-1000-8000-00805f9b34fb`.

// [Service UUID: Philips Lighting B.V. (0xfe0f)]
// [UUID: 97fe656120014f6286e9b71ee2da3d22]  - write 01 to enable pairing requests
// Read Power State Characteristic to initiate pairing request

// 932C32BD-0000-47A2-835A-A8D455B859DD Control Service, contains both characteristics
// 932C32BD-0002-47A2-835A-A8D455B859DD Power State Characteristic
// 932C32BD-0007-47A2-835A-A8D455B859DD Brightness and Color Temperature Characteristic


== Examples

=== Power state

[source,shell]
----
❯ nc -U /tmp/blemacd.sock <<< fe0f/59dd/0002
00
----

Toggle

[source,shell]
----
❯ nc -U /tmp/blemacd.sock <<< fe0f/59dd/0002/!
Ok(())
----

=== Brightness

1 byte, range 1 - 254 (`01` - `fe`)

[source,shell]
----
❯ nc -U /tmp/blemacd.sock <<< fe0f/32bd/0007[5]
fe

❯ nc -U /tmp/blemacd.sock <<< fe0f/32bd/0007[5]/+30[1..254]
Ok(())
----

=== Color temperature

2 bytes, in https://en.wikipedia.org/wiki/Mired[mired units], range 153-454 (`9900` - `c601`)

[source,shell]
----
❯ nc -U /tmp/blemacd.sock <<< fe0f/32bd/0007[8..]
9a00

❯ nc -U /tmp/blemacd.sock <<< fe0f/32bd/0007[8..]/+40[153..454]
Ok(())
----

== References

* https://github.com/npaun/philble[Python 3 library at Github]
* https://github.com/Mic92/hue-ble-ctl/blob/master/hue-ble-ctl.py[Another Python script at Github]
* https://github.com/aknowles18/magic-wand/blob/master/philipsHueBluetoothInstructions.md[Discovered service and characteristics UIDS]

== Troubleshooting

Bluetooth logs location on my Pixel 3 with Android 11

----
/data/misc/bluetooth/logs
----


