= Usage

WARNING: Documentation below is a draft.As such, it is not implemented yet and subject to change.

== Starting up

[source,shell]
----
blemacd [options]
----

=== Options

`--path /tmp/blemacd.sock`::
Specifies the path for Unix Socket. `/tmp/blemacd.sock` is the default.

== Stopping

TODO

== Usage

=== Issuing commands

Commands are issued by writing text-based commands to the socket.
I.e. with `nc`:

Connect socket and input/output via std.

[source,shell]
----
❯ nc -U /tmp/blemacd.sock
----

List all discovered peripherals and exit.

[source,shell]
----
❯ nc -U /tmp/blemacd.sock <<< all
----

=== Commands

`status`::
Returns daemon status

`all`::
List of peripherals discovered

`connected`::
List of connected peripherals

=== Addressing

Whenever input doesn't match a command, it is treated as a bluez-like path, `<peripheral>/<SERVICE>/<CHARACTERISTIC>`.

`<peripheral>`::
Daemon will try to match input string to peripheral UUID and if there is a match, will connect to that peripheral.

[source,shell]
----
❯ nc -U /tmp/blemacd.sock <<< f69
connected to peripheral [472df789-71f0-4d87-a47f-4e818ba79f69] (Hue ambiance lamp)
----

It is also possible to connect to peripheral by service UUID:

[source,shell]
----
❯ nc -U /tmp/blemacd.sock <<< :fe0f
connected to peripheral [472df789-71f0-4d87-a47f-4e818ba79f69] (Hue ambiance lamp) by service [fe0f]
----

`<peripheral>/<service>`::
Locate a service at peripheral.

[source,shell]
----
❯ nc -U /tmp/blemacd.sock <<< f69/32bd
service found: Service { id: Uuid(932c32bd-0000-47a2-835a-a8d455b859dd), primary: false, service: CBService(0x7ff25b605ae0) }
----

`<peripheral>/<service>/<characteristic>`::
Read a specified characteristic.
Result is in hex format.

[source,shell]
----
❯ nc -U /tmp/blemacd.sock <<< f69/32bd/0007
01010002017703029900
----

It is possible to specify range for characteristic:

[source,shell]
----
❯ nc -U /tmp/blemacd.sock <<< f69/32bd/0007[5]
77
❯ nc -U /tmp/blemacd.sock <<< f69/32bd/0007[8..]
9900
----

`<peripheral>/<service>/<characteristic>/<value>`::
Write a value to characteristic.
